services:
  terraform:
    image: hashicorp/terraform:1.6.2
    volumes:
      - ./setup:/tf/setup
      - ./deploy:/tf/deploy
      # for windows users, comment the line below and uncomment the line above
      #- ${USERPROFILE}/.aws:/root/.aws
    working_dir: /tf
    environment:
      # for windows users, comment the line below
      #- AWS_PROFILE=recipe-app
      - AWS_ACCESS_KEY_ID=${{ vars.AWS_ACCESS_KEY_ID }}
      - AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - AWS_DEFAULT_REGION=ap-southeast-1
      - TF_WORKSPACE=${TF_WORKSPACE}
      #- HOME=/root